### ISSUE TITLE
Error on Lesson 1.3

### ISSUE THREAD

**Issue by jfullmer1** [brianray/bakepie#1]
Found an error.  How do I fix it?
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-f33ebd42dccd> in <module>()
----> 1 import complete_pie

C:\Users\...\bakepie-master\bakepie-master\complete_pie.py in <module>()
      9 import prettytable
     10 
---> 11 from output import (LargeItem,
     12                     IngredientBase,
     13                     Liquid,

ImportError: No module named 'output'

**Comment by brianray** [comment]
I apologize there was a missing file at the time when you obtained the sources. You can insert this code in a cell to fix the issue from the notebook:

```
import urllib.request as request

url = 'https://raw.githubusercontent.com/brianray/bakepie/master/output.py'
page = request.urlopen(url)
with open('output.py', 'wb') as output:
    output.write(page.read())
```
Please confirm that works and I will close the issue.

**Comment by umneycreep** [comment]
![error in lesson 1 - copy](https://cloud.githubusercontent.com/assets/26616059/24254323/d7f0bbac-0f9f-11e7-85dd-9b7f362162d2.jpg)
Still doesn't appear to work for me.

**Comment by brianray** [comment]
here is the corrected code:

```python
import urllib.request as request

url = 'https://raw.githubusercontent.com/brianray/bakepie/master/output.py'
page = request.urlopen(url)
with open('output.py', 'wb') as output:
    output.write(page.read())
```

**Comment by umneycreep** [comment]
Working now. Thanks!

**Comment by brianray** [comment]
👍

**Comment by jfullmer1** [comment]
Also working for me.  Thank you!
